name: clickevents
favicon: null
layout_spectrum: 0.035076133674010634
typography_spectrum: 0.35947122098878026
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19159959955140948
  lightness: 0.4549795528873801
  saturation: 0.18549844971857965
  rhythmicContrast: 0.4348680751863867
purpose: []
